# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20230904-133348-linear-BLT

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "DIETClassifier"
    epochs: 100  # Đây là nơi bạn có thể giảm số epochs
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 100  # Cũng có thể giảm số epochs ở đây

policies:
  - name: "MemoizationPolicy"
  - name: "TEDPolicy"
    max_history: 70
    epochs: 100  # Và ở đây
