version: '3.0'

services:
  rasa:
    build:
      context: .
      dockerfile: /rasa-setup/Dockerfile
    container_name: rasa
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./rasa-app-data/models:/app/models"
    - "./rasa-app-data/logs:/app/logs"
    command: "run --enable-api --cors '*' --debug"
    user: root

  rasa_ui:       
    image: paschmann/rasa-ui:latest
    container_name: rasa_ui
    networks: ['rasa-network']
    ports:
      - "5001:5001"
    depends_on:
      - "rasa"
    environment:
      rasa_endpoint: "http://rasa:5005"

# thực hiện train data đẩy model vô rasa để xử lý, sẽ phải đợi lâu
# setup file với thư mục như mẫu
  rasa_train:
    container_name: rasa_train
    build:
      context: .
      dockerfile: /rasa-setup/Dockerfile
    networks: ['rasa-network']
    volumes:
      - "./rasa-app-data:/app"
    command: "train"
    depends_on:
      - "rasa"


networks: {rasa-network: {}}