recipe: default.v1
assistant_id: form_bot
language: vi

pipeline:
- name: WhitespaceTokenizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  token_pattern: (?u)\b\w+\b
- name: DucklingEntityExtractor
  url: http://duckling:8000
  dimensions:
  - number
- name: DIETClassifier
  epochs: 1
  run_eagerly: True
- name: EntitySynonymMapper
# - name: "rasa.shared.nlu.training_data.formats.openai.transformers_tokenizer.OpenAIAutoTokenizer"
#   model_name: "vinai/phobert-base"

policies:
- name: TEDPolicy
  epochs: 1
- name: AugmentedMemoizationPolicy
- name: RulePolicy
cors:
  enabled: true
  allow_origins:
  - "*"
  allow_credentials: false
  allow_methods:
  - "OPTIONS"
  - "GET"
  - "POST"
  allow_headers:
  - "*"
